service: dymek-api

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["MarkersDynamoDBTable", "Arn" ] }
  environment:
    MARKERS_TABLE: ${self:custom.tableName}
    DEV_DB_PORT: ${self:custom.dynamodb.start.port}

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpackIncludeModules: true
  tableName: 'markers-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
      port: 9123

functions:
  markers:
    handler: server/index.handler
    events:
      - http:
          path: /api/markers
          method: get
          cors: true
      - http:
          path: /api/markers
          method: post
          cors: true
  users:
    handler: server/index.handler
    events:
      - http:
          path: /api/users
          method: post
          cors:
            origins:
              - http://localhost
              - https://deevjjctzmtc1.cloudfront.net
      - http:
          path: /api/users
          method: get
          cors:
            origins:
              - http://localhost
              - https://deevjjctzmtc1.cloudfront.net

resources:
  Resources:
    MarkersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
