service: dymek-api

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { Fn::GetAtt: ["MarkersDynamoDBTable", "Arn"] }
        - { Fn::GetAtt: ["UsersDynamoDBTable", "Arn"] }
        - { Fn::Join: [ "/", [{ Fn::GetAtt: ["MarkersDynamoDBTable", "Arn"] }, 'index/geohash-index' ] ]}
        - { Fn::Join: [ "/", [{ Fn::GetAtt: ["MarkersDynamoDBTable", "Arn"] }, 'index/id-index' ] ]}
        - { Fn::Join: [ "/", [{ Fn::GetAtt: ["MarkersDynamoDBTable", "Arn"] }, 'index/userId-createdAt-index' ] ]}
  environment:
    MARKERS_TABLE: ${self:custom.markersTableName}
    USERS_TABLE: ${self:custom.usersTableName}
    DEV_DB_PORT: ${self:custom.dynamodb.start.port}
    GCLOUD_PROJECT: dymek-web-1519202400328

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  markersTableName: 'markers-table-${self:provider.stage}-geo'
  usersTableName: 'users-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
      port: 9123

functions:
  markers:
    handler: server/index.handler
    events:
      - http:
          path: /api/q
          method: get
          cors:
            origins:
              - '*'
            headers:
              - x-dymek-user-id
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
      - http:
          path: /api/q
          method: post
          cors:
            origins:
              - '*'
            headers:
              - x-dymek-user-id
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
    allowCredentials: false


resources:
  Resources:
    MarkersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: hashKey
            AttributeType: N
          -
            AttributeName: createdAt
            AttributeType: S
          -
            AttributeName: geohash
            AttributeType: N
          -
            AttributeName: userId
            AttributeType: S
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: hashKey
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        LocalSecondaryIndexes:
          -
            IndexName: 'geohash-index'
            KeySchema:
              -
                KeyType: HASH
                AttributeName: hashKey
              -
                KeyType: RANGE
                AttributeName: geohash
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          -
            IndexName: userId-createdAt-index
            KeySchema:
              -
                AttributeName: userId
                KeyType: HASH
              -
                AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          -
            IndexName: id-index
            KeySchema:
              -
                AttributeName: id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 5
        TableName: ${self:custom.markersTableName}
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.usersTableName}
